ROOT=/home/preeti/CMU/Assignments/Fall2015/15740/Project/stacklets

LIBLOCK = $(ROOT)/liblock

CFLAGS  += -g -I$(LIBLOCK)

ifeq ($(shell uname),Linux)
LIBS=-lpapi -lnuma -luli
else
LIBS=-lposix4
endif

#LDFLAGS += -L/usr/local/lib/ -L/usr/lib64/ -L$(ROOT)/liblock -Wl,-rpath=$(realpath $(ROOT)/liblock) -Wl,-rpath=/usr/local/lib -Wl,-rpath=/usr/lib64 -pthread -rdynamic $(LIBS)

Echo=@echo [$(PROJECT)]: 

ifndef VERBOSE
  Verb := @
endif
